# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7]
        pyspark-version: [2.4.5, 2.4.6, 3.0.0]
    steps:
    - uses: actions/checkout@v2
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: anaconda, conda-forge
    - run: conda --version
    - run: which python
    - name: Install dependencies
      run: |
        conda install pyspark=${{ matrix.pyspark-version }}
        pip install -e .
    - name: Test with unittest
      run: |
        cd $GITHUB_WORKSPACE/sparkxgb/tests && python -m unittest classifier.py
